version: '3.8'

services:
  app:
    image: hello-front-dev
    restart: always
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: Dockerfile
    ports:
      - 3000:80
    container_name: hello-front-dev